### ISSUE TITLE
unable to checkout / compile

### ISSUE THREAD

**Issue by proukakis** [WeichenZhou/PALMER#13]
**Describe the bug**
cannot checkout from git

**To Reproduce**
git clone https://github.com/mills-lab/PALMER.git
Cloning into 'PALMER'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 610 (delta 9), reused 0 (delta 0), pack-reused 583
Receiving objects: 100% (610/610), 74.39 MiB | 10.85 MiB/s, done.
Resolving deltas: 100% (293/293), done.
git-lfs smudge 'index/Alu.regions.GRCh37': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: index/Alu.regions.GRCh37: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Then trying to unzip directory

and use make as below (or owthout specifying compilers)

make CC=gcc-6 CXX=g++-6
rm -f PALMER
g++ -o PALMER PALMER.v1.4.cpp

PALMER.v1.4.cpp:396:20: error: variable length array of non-POD element type
      'string' (aka 'basic_string<char, char_traits<char>, allocator<char> >')
    string chr_inde[line_chr];
                   ^
1 error generated.
make: *** [PALMER] Error 1

**Additional context**
Please note I am using Mac OS. Perhaps this is the problem, but i still don't understand why the git clone would fail. I have access to Linux if you think this will fix it.

thanks
christos

**Comment by WeichenZhou** [comment]
Hi Christos,
Thanks for your posting.
Could you please check the directory /PALMER/index to see whether there are files downloaded (MB size level)? If not, I think ONE reason would be you need git-lfs to download all files. I will re-upload the files and make sure the downloading does not require lfs anymore. If you have successfully downloaded all files (including index files) and still have the same problem, please let me know. 

Thanks
Arthur

**Comment by proukakis** [comment]
yes, the index files are not there, sounds like this is the problem, thanks

**Comment by WeichenZhou** [comment]
You might wanna try to install git-lfs to download the full package and immediately use PALMER. In the meantime, I will update the files ASAP.
Thanks!!

**Comment by proukakis** [comment]
Yes will do tomorrow, Thanks

Sent from my iPhone so please forgive brevity and any errors
________________________________

**Comment by WeichenZhou** [comment]
Close this issue.

**Comment by proukakis** [comment]
hello, i know this is closed, but i tried the install just now on mac with the latest version and it seems to work!

**Comment by WeichenZhou** [comment]
Thanks.
