### ISSUE TITLE
BLAST engine error: Warning: Sequence contains no data 

### ISSUE THREAD

**Issue by Soniazumalave** [WeichenZhou/PALMER#14]
I am getting these warnings when running PALMER:

> BLAST engine error: Warning: Sequence contains no data 
> BLAST engine error: Warning: Sequence contains no data 
> BLAST engine error: Warning: Sequence contains no data 
> BLAST engine error: Warning: Sequence contains no data 
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 69
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 63
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 73
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 61
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 61
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 63
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 73
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 72
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 72
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 56
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 69
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 72
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 72
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 62
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 72
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 74
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 70
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 69
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 72
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 61
> Warning: (1431.1) CFastaReader: Ignoring invalid residue  at line 2, position 57

The command I use is:
./PALMER --input $sampleBam --workdir $wkDir/ --ref_ver hg19 --output NA12878 --type LINE --chr 21 --ref_fa $refFasta

And the PALMER version is 1.4.

I've read it is related to the presence of ambiguous nucleotides (N's) in the reference genome. Which reference do you use? Is it masked? Would these warnings affect the results?

The head of my reference looks like this:

> >1 dna:chromosome chromosome:GRCh37:1:1:249250621:1
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

Thank you in advance!

**Comment by WeichenZhou** [comment]
Hi Sonia,

Thanks for using PALMER. The head of the reference should be as what you saw. And your command line looks good too.
The error information from BLAST sometime happens, because of the string of 'N'. Yet, it should not affect your final results.

Let me know if you have any further questions!
Cheers
