### ISSUE TITLE
BLAST too many postional arguments

### ISSUE THREAD

**Issue by chadsmith123** [WeichenZhou/PALMER#15]
**Describe the bug**
Error:  (CArgException::eSynopsis) Too many positional arguments (1), the offending value: /fastscratch/smithch/beck-lab/Mice/PacBio/palmer/PWD_CHRX2/PALMER//chrX_1_1000000/SEQ.masked

**To Reproduce**
+ /projects/balacp/tools/PALMER/PALMER --input /fastscratch/smithch/beck-lab/Mice/PacBio/palmer/PWD_CHRX2/m64039_200121_201039_mm10_ngmlr.sorted.bam --workdir /fastscratch/smithch/beck-lab/Mice/PacBio/palmer/PWD_CHRX2/PALMER// --output m64039_200121_201039_mm10_ngmlr_palmer_chrX_LINE --ref_ver other --ref_fa /projects/beck-lab/reference/mm10/mm10_canonical.fa --chr chrX --custom_index /projects/beck-lab/chad/Mice/mm10/mm10_ucsc_repeatmasker_LINE.bed --custom_seq /projects/beck-lab/chad/Mice/mm10/MELT/LINE/L1MdA_consensus.fa

**Desktop (please complete the following information):**
 - PALMER v1.4

**Additional context**
Using --custom-seq flag and BLAST 2.9.0+

[stderr.txt](https://github.com/WeichenZhou/PALMER/files/4506206/stderr.txt)
[stdout.txt](https://github.com/WeichenZhou/PALMER/files/4506213/stdout.txt)

**Comment by WeichenZhou** [comment]
Hi Chad!

Sorry for the delay. 

Did you get any sub-folders in your working directory? If yes, does it have any files? If no, would you try the working directory as '''--workdir /fastscratch/smithch/beck-lab/Mice/PacBio/palmer/PWD_CHRX2/PALMER/''' not '''--workdir /fastscratch/smithch/beck-lab/Mice/PacBio/palmer/PWD_CHRX2/PALMER//'''

Thanks!
Arthur

**Comment by WeichenZhou** [comment]
In addition, it seems missing a parameter '--type' as input. As I can see here, it would be '--type CUSTOMIZED'. And you want to open TSD finder option as well: '--TSD_finding TRUE', since you still want to find out the retrotransposition events.

Here is an example when I ran PALMER for NumtS in Chimpanzee:
'''./PALMER --input $DirPath/your.bam.file --workdir $DirPath/ --ref_ver other --output your.output.prefix --chr chr5 --ref_fa $your.reference.file.path/your.reference.fa --type CUSTOMIZED --custom_seq $your.custom_seq.file.path/Clint.mt'''

**Comment by WeichenZhou** [comment]
I added one more example in the readme file, please try the example here:
```
./PALMER --input $DirPath/your.bam.file --workdir $DirPath/ --output your.output.prefix --chr chrX --ref_ver other --ref_fa $your.reference.file.path/your.reference.fa --type CUSTOMIZED --custom_seq $your.custom_seq.file.path/L1MdA_consensus.fa --custom_index $your.custom_index.file.path/mm10_ucsc_repeatmasker_LINE.bed --TSD_finding TRUE
```
Also, if it still not working, that would be good if you could provide us a ref fasta and a sample BAM so we can trouble shoot locally.

Thanks!

**Comment by WeichenZhou** [comment]
Will close it if no more discussion in this issue.

**Comment by WeichenZhou** [comment]
Close the issue.
