### ISSUE TITLE
warning blastn invalid query sequence

### ISSUE THREAD

**Issue by jainy** [WeichenZhou/PALMER#16]
**Describe the bug**
I get this message during my PALMER run:

Warning: [blastn] Query_1 m54336U_200507_18.. : Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options

**To Reproduce**
1. What's your data '...'
2. What's your command line '....'
/home/jainy/software/PALMER/PALMER --input /ybod2/jainy/Project4/U-87/ref-hg38-U_87-pbreads.bam --workdir /ybod2/jainy/Project4/PALMERanalysis/U-87/ALU/ --ref_ver GRCh38 --output hg38.U-87_cell_line.ALU. --type ALU --chr chr19 --ref_fa /ybod2/jainy/Project4/refgenome_hg38_decoy/GRCh38_no_alt_plus_hs38d1.fa

3. How long is the running time '....'
Variant type is ALU
Working directory is /ybod2/jainy/Project4/PALMERanalysis/U-87/ALU/
Input file is /ybod2/jainy/Project4/U-87/ref-hg38-U_87-pbreads.bam
Output file is /ybod2/jainy/Project4/PALMERanalysis/U-87/ALU/hg38.U-87_cell_line.ALU.
Running on chr19
ref is GRCh38
THERE ARE 59 REGIONS TO COUNT.
Pre-masking step & single read calling step is initiated.
Working in the direcotry mkdir /ybod2/jainy/Project4/PALMERanalysis/U-87/ALU/chr19_1_1000000/.
1. Samtools Step for region chr19_1_1000000 now completed.
Pre-masking step for chr19_1_1000000 completed.
Blastn Step for region chr19_1_1000000 completed.
Single read calling step for chr19_1_1000000 completed.
TSD_module step for chr19_1_1000000 completed.
Warning: [blastn] Query_1 m54336U_200507_18.. : Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options
Warning: [blastn] Query_1 m54336U_200507_18.. : Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options
Warning: [blastn] Query_1 m54336U_200512_03.. : Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - PALMER Version [e.g. v1.6]

**Additional context**

**Comment by WeichenZhou** [comment]
Hi Jainy,

Sorry for the delay. As I said, I think the warning should be fine for your runs as long as you got outputs. Sometimes, PALMER will grep the sequence vector with no empty sequences there or with Ns.

If you are not sure about the output, please post here and I'm happy to check for you!

Arthur

**Comment by WeichenZhou** [comment]
Contact through email. Close the issue.
