### ISSUE TITLE
Question: how are TE sequences obtained?

### ISSUE THREAD

**Issue by gbdias** [WeichenZhou/PALMER#18]
Dear @WeichenZhou ,

I couldn't determine from the documentation how the TE sequence reported in https://github.com/WeichenZhou/PALMER/blob/master/example/sample_TSD_reads.txt is obtained (i.e. the sequence in the `Whole_insertion_seq ` field).
Is that a consensus of TE-supporting reads? Or is it a representative sequence from the pool of TE-supporting reads? Or maybe the result of a local assembly?

Thank you

**Comment by WeichenZhou** [comment]
Hi @gbdias,

Yes, as you mentioned, it is a representative sequence from the pool of TE-supporting reads.

Best

**Comment by gbdias** [comment]
Thank you @WeichenZhou
