### ISSUE TITLE
Installing erro

### ISSUE THREAD

**Issue by huangyuanf** [WeichenZhou/PALMER#19]
**Describe the bug**
 When I installed samtools=1.8,gif-lfs by conda ,I installed ncbi-blast-2.12.0+ by downloaded its code, then I installed PALMER 1.6 by downloading codes in this page！when I run /lustre/huangyf/software/PALMER-1.6/PALMER --input /lustre/huangyf/HG002/HG002-ONT-60X/Hg002.ONT.minimap2/Hg002.ONT.minimap2.bam/Hg002.sort.bam --workdir /lustre/huangyf/HG002/TE.out/mi-palmer-TE/ONT/LINE/ --output /lustre/huangyf/HG002/TE.out/mi-palmer-TE/ONT/LINE/output.prefix --ref_ver GRCh38 --type LINE  --ref_fa /lustre/huangyf/HG002/genome/ucsc.hg38.fa 
 I got such information:
blastn:command not found
 when I run blastn only it can run well,so could  you help resolve it?Thanks very much

**Comment by WeichenZhou** [comment]
Hi @huangyuanf,

Thank you for using PALMER. Where did you install blastn? Can you call blastn by using command line 'blastn' by default in your system?

Thanks!

**Comment by WeichenZhou** [comment]
Please make sure you can run blastn outside of PALMER and you run PALMER in the same environment as blastn.

Thanks!
