### ISSUE TITLE
Somatic MEIs

### ISSUE THREAD

**Issue by jiadong324** [WeichenZhou/PALMER#23]
Dear Author,

I am wondering if I can use PALMER to detect somatic LINE from matched normal-tumor pair samples.

Thanks!

**Comment by WeichenZhou** [comment]
Hi Jiadong,

Thanks for using PALMER. The current version is not designed for somatic MEI detection, but you can definitely use it to extract all the potential somatic MEI signals in your long-read sequenced tumor samples. By comparing the signals from control and case samples, it would potentially give you a list of putative somatic MEIs.

Let me know if you have any further questions! Or feel free to send me emails!!

Best,
Arthur

**Comment by jiadong324** [comment]
Thanks for your quick response! It's a nice tool and easy to run.
