### ISSUE TITLE
Running error!

### ISSUE THREAD

**Issue by tjiangHIT** [WeichenZhou/PALMER#7]
when i run PALMER, I gain one error as bellow:
**BLAST engine error: Empty CBlastQueryVector
Pre-masking step & single read calling step for 1_122000001_123000000 completed.
TSD_module step for 1_122000001_123000000 completed.
CANNOT OPEN FILE**

How can fix it?
Thanks

**Comment by WeichenZhou** [comment]
Hi Jiang,
Thanks for using PALMER, tho I don't know how you find it..lol
I have updated the scripts. Please clone the new one and try to run on your data. If you have any questions, feel free to let me know.

Best,
Weichen
